Обновил leiningen.

diff --git a/lein b/lein
--- a/lein
+++ b/lein
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-VERSION="1.0.1"
+VERSION="1.1.0"
 
-CLASSPATH="$(find -H lib/ -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
+CLASSPATH="$(find lib/ -follow -mindepth 1 -maxdepth 1 -print0 2> /dev/null | tr \\0 \:)"
 LEIN_JAR="$HOME/.m2/repository/leiningen/leiningen/$VERSION/leiningen-$VERSION-standalone.jar"
-CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.1.0-master-SNAPSHOT/clojure-1.1.0-master-SNAPSHOT.jar"
+CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.1.0/clojure-1.1.0.jar"
 
 # normalize $0 on certain BSDs
 if [ "$(dirname $0)" = "." ]; then
@@ -58,8 +58,20 @@ for ARG in "$@"; do
   ESCAPED_ARGS="$ESCAPED_ARGS"' "'$(echo $ARG | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')'"'
 done
 
+HTTP_CLIENT="wget -O"
+if type -p curl >/dev/null 2>&1; then
+    HTTP_CLIENT="curl -L -o"
+fi
+
 if [ "$1" = "repl" ]; then
-    java -client $JAVA_OPTS -cp "src/:classes/:$CLASSPATH" jline.ConsoleRunner clojure.main ${@:2}
+    if [ -r project.clj ]; then
+        echo "Warning: the repl task currently doesn't honor some project.clj"
+        echo "options due to I/O stream issues. Future versions will address"
+        echo "this, but for now you will get more consistent behaviour from repls"
+        echo "launched by either the lein-swank plugin or the lein-nailgun plugin."
+        echo
+    fi
+    $RLWRAP java -client $JAVA_OPTS -cp "src/:classes/:$CLASSPATH" jline.ConsoleRunner clojure.main ${@:2}
 elif [ "$1" = "self-install" ]; then
     if [[ $VERSION == *SNAPSHOT ]]; then
         echo "The self-install task is only meant for stable releases."
@@ -68,11 +80,34 @@ elif [ "$1" = "self-install" ]; then
     fi
     echo "Downloading Leiningen now..."
     mkdir -p `dirname "$LEIN_JAR"`
-    LEIN_URL="http://repo.technomancy.us/leiningen-$VERSION-standalone.jar"
-    if type -p curl >/dev/null 2>&1; then
-        exec curl -o "$LEIN_JAR" "$LEIN_URL"
+    LEIN_URL="http://github.com/downloads/technomancy/leiningen/leiningen-$VERSION-standalone.jar"
+    exec $HTTP_CLIENT "$LEIN_JAR" "$LEIN_URL"
+elif [ "$1" = "upgrade" ]; then
+    if [[ $VERSION == *SNAPSHOT ]]; then
+        echo "The upgrade task is only meant for stable releases."
+        echo "See the \"Hacking\" section of the README."
+        exit 1
+    fi
+    if [ ! -w "$SCRIPT" ]; then
+        echo "You do not have permission to upgrade the installation in $SCRIPT"
+        exit 1
     else
-        exec wget -O "$LEIN_JAR" "$LEIN_URL"
+        echo "The script at $SCRIPT will be upgraded to the latest stable version."
+        echo -n "Do you want to continue [Y/n]? "
+        read RESP
+        case "$RESP" in
+            y|Y|"")
+                echo
+                echo "Upgrading..."
+                LEIN_SCRIPT_URL="http://github.com/technomancy/leiningen/raw/stable/bin/lein"
+                $HTTP_CLIENT "$SCRIPT" "$LEIN_SCRIPT_URL" \
+                    && chmod +x "$SCRIPT" \
+                    && echo && $SCRIPT self-install && echo && echo "Now running" `$SCRIPT version`
+                exit $?;;
+            *)
+                echo "Aborted."
+                exit 1;;
+        esac
     fi
 else
     exec java -Xbootclasspath/a:"$CLOJURE_JAR" -client $JAVA_OPTS -cp "$CLASSPATH" -Dleiningen.version="$VERSION" clojure.main -e "(use 'leiningen.core)(-main $ESCAPED_ARGS)"
