Update Leiningen to 1.2.0.

diff --git a/lein b/lein
--- a/lein
+++ b/lein
@@ -1,10 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-VERSION="1.1.0"
+VERSION="1.2.0"
 
-CLASSPATH="$(find lib/ -follow -mindepth 1 -maxdepth 1 -print0 2> /dev/null | tr \\0 \:)"
+CLASSPATH="$(ls -1 lib/dev/*jar 2> /dev/null | tr \\n \:)":src/:$CLASSPATH
 LEIN_JAR="$HOME/.m2/repository/leiningen/leiningen/$VERSION/leiningen-$VERSION-standalone.jar"
-CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.1.0/clojure-1.1.0.jar"
+CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.2.0-beta1/clojure-1.2.0-beta1.jar"
+NULL_DEVICE=/dev/null
 
 # normalize $0 on certain BSDs
 if [ "$(dirname $0)" = "." ]; then
@@ -24,18 +25,26 @@ while [ -h "$SCRIPT" ] ; do
     fi
 done
 
+ORIGINAL_PWD=$PWD
+while [ ! -r "$PWD/project.clj" ] && [ "$PWD" != "/" ] && [ ! $NOT_FOUND ]
+do
+    cd ..
+    if [ "$(dirname $PWD)" == "/" ]; then
+        NOT_FOUND=0
+        cd $ORIGINAL_PWD
+    fi
+done
+
 BIN_DIR="$(dirname "$SCRIPT")"
 
 if [ -r "$BIN_DIR/../src/leiningen/core.clj" ]; then
     # Running from source checkout
     LEIN_DIR="$(dirname "$BIN_DIR")"
     LEIN_LIBS="$(find -H $LEIN_DIR/lib -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
-    CLASSPATH="$LEIN_DIR/src:$LEIN_LIBS:$CLASSPATH"
+    CLASSPATH="$LEIN_DIR/src:$LEIN_LIBS:$CLASSPATH:$LEIN_JAR"
 
-    if [ "$LEIN_LIBS" = "" -a "$1" != "self-install" ]; then
-        echo "Your Leiningen development checkout is missing its dependencies."
-        echo "Please download a stable version of Leiningen to fetch the deps."
-        echo "See the \"Hacking\" section of the readme for details."
+    if [ "$LEIN_LIBS" = "" -a "$1" != "self-install" -a ! -r "$LEIN_JAR" ]; then
+        echo "Leiningen is missing its dependencies. Please run \"lein self-install\"."
         exit 1
     fi
 else
@@ -48,38 +57,27 @@ else
     fi
 fi
 
+# Convert classpath to Windows format when running on Cygwin
+if [ "$OSTYPE" = "cygwin" ]; then
+    CLASSPATH=`cygpath -wp $CLASSPATH`
+    CLOJURE_JAR=`cygpath -wp $CLOJURE_JAR`
+fi
+
 if [ $DEBUG ]; then
     echo $CLASSPATH
 fi
-
-# escape command-line arguments so they can be evaled as strings
-ESCAPED_ARGS=""
-for ARG in "$@"; do
-  ESCAPED_ARGS="$ESCAPED_ARGS"' "'$(echo $ARG | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')'"'
-done
 
 HTTP_CLIENT="wget -O"
 if type -p curl >/dev/null 2>&1; then
     HTTP_CLIENT="curl -L -o"
 fi
 
-if [ "$1" = "repl" ]; then
-    if [ -r project.clj ]; then
-        echo "Warning: the repl task currently doesn't honor some project.clj"
-        echo "options due to I/O stream issues. Future versions will address"
-        echo "this, but for now you will get more consistent behaviour from repls"
-        echo "launched by either the lein-swank plugin or the lein-nailgun plugin."
-        echo
-    fi
-    $RLWRAP java -client $JAVA_OPTS -cp "src/:classes/:$CLASSPATH" jline.ConsoleRunner clojure.main ${@:2}
-elif [ "$1" = "self-install" ]; then
-    if [[ $VERSION == *SNAPSHOT ]]; then
-        echo "The self-install task is only meant for stable releases."
-        echo "See the \"Hacking\" section of the README."
-        exit 1
-    fi
+JAVA_CMD=${JAVA_CMD:-"java"}
+
+if [ "$1" = "self-install" ]; then
     echo "Downloading Leiningen now..."
-    mkdir -p `dirname "$LEIN_JAR"`
+    LEIN_DIR=`dirname "$LEIN_JAR"`
+    mkdir -p "$LEIN_DIR"
     LEIN_URL="http://github.com/downloads/technomancy/leiningen/leiningen-$VERSION-standalone.jar"
     exec $HTTP_CLIENT "$LEIN_JAR" "$LEIN_URL"
 elif [ "$1" = "upgrade" ]; then
@@ -110,5 +108,25 @@ elif [ "$1" = "upgrade" ]; then
         esac
     fi
 else
-    exec java -Xbootclasspath/a:"$CLOJURE_JAR" -client $JAVA_OPTS -cp "$CLASSPATH" -Dleiningen.version="$VERSION" clojure.main -e "(use 'leiningen.core)(-main $ESCAPED_ARGS)"
+    if type -p cygpath >/dev/null 2>&1; then
+        # When running on Cygwin, use Windows-style paths for java
+        CLOJURE_JAR=`cygpath -w "$CLOJURE_JAR"`
+        CLASSPATH=`cygpath -wp "$CLASSPATH"`
+	    NULL_DEVICE=NUL
+    fi
+
+    if [ "$1" = "repl" ] && [ -z $INSIDE_EMACS ] && [ $TERM != "dumb" ]; then
+        # Use rlwrap if it's available, otherwise fall back to JLine
+        RLWRAP=`which rlwrap`
+        if [ $? -eq 1 ]; then
+            JLINE=jline.ConsoleRunner
+        fi
+    fi
+
+    # The -Xbootclasspath argument is optional here: if the jar
+    # doesn't exist everything will still work, it will just have a
+    # slower JVM boot.
+    exec $RLWRAP $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client $JAVA_OPTS \
+                      -cp "$CLASSPATH" -Dleiningen.version="$VERSION" $JLINE \
+                      clojure.main -e "(use 'leiningen.core)(-main)" $NULL_DEVICE $@
 fi
